steps:
- id: Build-docker
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/frontend/admin:$SHORT_SHA', '.']
  timeout: 900s

- id: Push-docker
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/frontend/admin:$SHORT_SHA']
  timeout: 900s

- id: envSubst-for-deployment.yml
  name: 'gcr.io/$PROJECT_ID/envsubst'
  env:
    - 'SHORT_SHA=$SHORT_SHA'
    - 'PROJECT_ID=$PROJECT_ID'
  args: ['dev-deployment.yaml']

- id: Deploy-to-GKE
  name: "gcr.io/cloud-builders/gke-deploy" 
  args:
  - run
  - --filename=dev-deployment.yaml
  - --cluster=multi-apps
  - --location=asia-southeast1
  timeout: 900s

timeout: '3600s'

options:
  logging: CLOUD_LOGGING_ONLY
